version: "3.9"
services:
  wispo_api:
    container_name: wispo_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WISPO_API_ENV: dev
    ports:
      - "8989:8989"
    networks:
      - wispo_api

#  postgres:
#    image: postgres:17.0-alpine3.20
#    container_name: postgres
#    restart: unless-stopped
#    shm_size: 128mb
#    ports:
#      - "5432:5432"
#    volumes:
#      - "./postgres/data:/var/lib/postgres/data"
#    environment:
#      - POSTGRES_USER=wispo_api
#      - POSTGRES_PASSWORD=secret
#      - POSTGRES_DB=wispo_api
#    networks:
#      - wispo_api

#  redis:
#    image: "redis:7.4.1-alpine"
#    container_name: redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    networks:
#      - wispo_api

networks:
  wispo_api:
    driver: bridge
