services:
  wispo_api:
    container_name: wispo_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WISPO_API_ENV=dev
    ports:
      - "8989:8989"
    networks:
      - wispo-api-network
    entrypoint: ["/bin/sh", "-c", "/opt/wispo_api/_rel/wispo_api_release/bin/wispo_api_release foreground"]
networks:
  wispo-api-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16