= Wispo API
:toc:

== About

`Wispo API` server provides `HTTP REST` APIs which is available at `/rest/1` endpoints on `8989` port number.
Configuration file is `config/sys.config`.

== How to start

.Start for development and debugging:
[source,shell,linenum]
----
$ cd wispo_api && make run
----

NOTE: Change `ip` and `port` values in `config/sys.config` file if required before starting.

.Start in Docker Compose:
[source,shell,linenum]
----
$ git clone git@github.com:plavno-plavno/wispo_api.git
$ cd wispo_api
$ checkout devel
$ docker compose -f docker-compose.yaml up
----

NOTE: `ip` value in `config/sys.config` file MUST be set to `{0,0,0,0}` for start under Docker Compose.


== Healthcheck for K8s

.Request:
[source,shell,linenum]
----
$ curl -X GET http://127.0.0.1:8989/rest/1/health/check \
-H 'Accept: application/json'
----

.Response:
[source,shell,linenum]
----
HTTP/1.1 200 OK
content-length: 69
content-type: application/json
date: Mon, 06 Jan 2025 02:20:12 GMT
server: Cowboy

{
  "status": "ok"
}'
----


== Register Phone

.Request:
[source,shell,linenum]
----
$ curl -X POST http://127.0.0.1:8989/rest/1/phones/register \
-H 'Content-Type: application/json' \
-d '
{
  "phone": "+1234567890"
}'
----

.Response:
[source,shell,linenum]
----
HTTP/1.1 200 OK
content-length: 69
content-type: application/json
date: Mon, 06 Jan 2025 02:20:12 GMT
server: Cowboy

{
  "status": "ok",
  "data": {
    "phone": "+1234567890",
    "code": [2,7,0,3,9,1]
  }
}'
----

== Confirm Phone

.Request:
[source,shell,linenum]
----
$ curl -X POST http://127.0.0.1:8989/rest/1/phones/confirm \
-H 'Content-Type: application/json' \
-d '
{
  "phone": "+1234567890",
  "code": [1,2,3,4,4,7]
}'
----

.Response:
[source,shell,linenum]
----
HTTP/1.1 200 OK
content-length: 69
content-type: application/json
date: Mon, 06 Jan 2025 02:20:12 GMT
server: Cowboy

{
  "status": "ok",
  "data": {
    "jid": "0923e1f4-fb61-3739-99c5-918c57656d5e@localhost",
    "access_jwt": "eyJhbGciOiJIUzI1NiIsInR5...",
    "access_jwt_expires_in": 1768366533,
    "refresh_jwt": "eyJhbGciOiJIUzI1NiIsInR...",
    "refresh_jwt_expires_in": 1768366533
  }
}'
----


== Refresh JWT

.Request:
[source,shell,linenum]
----
$ curl -X POST http://127.0.0.1:8989/rest/1/jwt/refresh \
-H 'Content-Type: application/json' \
-d '
{
  "refresh_jwt": "eyJhbGciOiJIUzI1NiIsI..."
}'
----

.Response:
[source,shell,linenum]
----
HTTP/1.1 200 OK
content-length: 601
content-type: application/json
date: Tue, 14 Jan 2025 04:55:33 GMT
server: Cowboy

{
    "status": "ok",
    "data": {
      "jid": "0923e1f4-fb61-3739-99c5-918c57656d5e@localhost",
      "access_jwt": "eyJhbGciOiJIUzI1NiIsInR5...",
      "access_jwt_expires_in": 1768366533,
      "refresh_jwt": "eyJhbGciOiJIUzI1NiIsInR...",
      "refresh_jwt_expires_in": 1768366533
    }
}
----


== Sync Contacts List

.Request:
[source,shell,linenum]
----
$ curl -X POST http://127.0.0.1:8989/rest/1/contacts/sync \
-H 'Content-Type: application/json' \
-d '
{
  "phone": "+1234567890",
  "contacts": ["+111222333", "+777888999", "+999333111"]
}'
----

.Response:
[source,shell,linenum]
----
HTTP/1.1 200 OK
content-length: 69
content-type: application/json
date: Mon, 06 Jan 2025 02:20:12 GMT
server: Cowboy

{
  "status": "ok",
  "data": {
    "access_jwt": "...",
    "refresh_jwt": "...",
  }
}'
----

== Remove Synced Contacts List

== Files Upload/Download

WARNING: Deprecated API. For development only.

.Upload file:
[source,shell,linenum]
----
$ curl -i -X POST http://localhost:8989/files \
-H "Content-Type: multipart/form-data" \
-F "data=@erlang-logo.png"

HTTP/1.1 204 No Content
----

.Download file:
[source,shell,linenum]
----
$ curl -i -X GET http://localhost:8989/images/erlang-logo.png
HTTP/1.1 200 OK
accept-ranges: bytes
content-length: 5737
content-type: image/png
date: Wed, 08 Jan 2025 12:03:35 GMT
etag: "1699637517"
last-modified: Wed, 08 Jan 2025 12:02:44 GMT
server: Cowboy

Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
----

NOTE: We can retrieve previously uploaded file using their file name.